[package]
name = "choco"
version = "0.1.0"
authors = ["Vincent Isambart <vincent.isambart@gmail.com>"]
edition = "2018"

[dependencies]
choco_macro = { path = "macro" }

[build-dependencies]
cc = "1.0"

[workspace]
members = [
    "macro",
]
