[package]
name = "choco_macro"
version = "0.1.0"
authors = ["Vincent Isambart <vincent.isambart@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
# syn = { version = "1.0", features = ["extra-traits"] }
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
